name: Keith MacLean
favicon: null
layout_spectrum: 0.8463327267672867
typography_spectrum: 0.030540721956640482
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1625065878033638
  lightness: 0.48255346715450287
  saturation: 0.5708242852706462
  rhythmicContrast: 0.6560501442290843
purpose: []
